[package]
name = "rust-cas"
version = "0.0.1"
authors = ["Coleton O'Donnell <contact@coleton.io>"]
keywords = ["cas", "math"]
repository = "https://github.com/coletonodonnell/rust-cas"
edition = "2018"